// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5FerZwklxc97rmL_-CLrBJWUNIEhbD-0',
    appId: '1:838679022810:web:b73840bb52a375b093a9e3',
    messagingSenderId: '838679022810',
    projectId: 'portfolio-15508',
    authDomain: 'portfolio-15508.firebaseapp.com',
    storageBucket: 'portfolio-15508.firebasestorage.app',
    measurementId: 'G-476FZNTZCM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVyLR5Tf0ltfF-7F8kvy7x2Ns3wBA2bMU',
    appId: '1:838679022810:android:c083c935674fae9193a9e3',
    messagingSenderId: '838679022810',
    projectId: 'portfolio-15508',
    storageBucket: 'portfolio-15508.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSJFH7XR9ft9VXqRswucXeQKb9ciY4KWQ',
    appId: '1:838679022810:ios:b4493cd3a7fb866f93a9e3',
    messagingSenderId: '838679022810',
    projectId: 'portfolio-15508',
    storageBucket: 'portfolio-15508.firebasestorage.app',
    iosBundleId: 'com.vishal.portfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSJFH7XR9ft9VXqRswucXeQKb9ciY4KWQ',
    appId: '1:838679022810:ios:b4493cd3a7fb866f93a9e3',
    messagingSenderId: '838679022810',
    projectId: 'portfolio-15508',
    storageBucket: 'portfolio-15508.firebasestorage.app',
    iosBundleId: 'com.vishal.portfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5FerZwklxc97rmL_-CLrBJWUNIEhbD-0',
    appId: '1:838679022810:web:cd0d0b052746e50a93a9e3',
    messagingSenderId: '838679022810',
    projectId: 'portfolio-15508',
    authDomain: 'portfolio-15508.firebaseapp.com',
    storageBucket: 'portfolio-15508.firebasestorage.app',
    measurementId: 'G-9G9618J19V',
  );

}